Failing workflow

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -21,6 +21,9 @@ jobs:
         id: fmt
         run: terraform fmt -check -list=true -recursive
 
+      - name: Fail intentionally
+        run: exit 1  # This will fail the workflow
+
       - name: Terraform init
         id: init
         run: terraform init
